name: Dark WorkFlow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PWD: ${{ secrets.DB_PWD }}
          USER: ${{ secrets.USER }}
          REPO: ${{ secrets.REPO }}
          MY_API: ${{ secrets.MY_API }}
          KEY: ${{ secrets.KEY }}
        run: |
          python app.py
